/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercise.sumup;

public class Library {

	public final static String SPAM = "I know that's an incredible statement, but bear with me while I \n"
			+ "explain. You have already deleted mail from dozens of \"Get Rich \n"
			+ "Quick\" schemes, chain letter offers, and LOTS of other \n"
			+ "absurd scams that promise to make you rich overnight with no \n" + "investment and no work.\n" + "\n"
			+ "My offer isn't one of those. What I'm offering is a \n"
			+ "straightforward computer-based service that you can run full-or \n"
			+ "part-time like a regular business. This service runs auto-\n"
			+ "matically while you sleep, vacation, or work a \"regular\" job. \n"
			+ "It provides a valuable new service for businesses in your area.\n" + "\n"
			+ "I'm offering a high-tech, low-maintenance, work-from-anywhere \n"
			+ "business that can bring in a nice comfortable additional income \n"
			+ "for your family. I did it for eight years. Since I started \n"
			+ "inviting others to join me, I've helped over 4000 do the same.\n" + "\n" + "http://www.abmailing.com\n"
			+ "Phone: 800-226-2770\n" + "\n" + "               Our Customers Say It Best\n" + "\n"
			+ "\"Your energy and drive are truly an inspiration to me and I'm \n"
			+ "sure to others also. Thanks for sharing your creation with us \n"
			+ "so we can all become successful... Keep up the good work!\" \n" + "C.G., Palos Hills, Il\n" + "\n"
			+ "\"Very few software providers freely disseminate information \n"
			+ "regarding future inclusions and upgrades like you do. Even \n"
			+ "fewer accept much input regarding potential changes and up-\n"
			+ "grades. you listen!\" M.K., Tampa, Fl\n" + "\n"
			+ "\"I'll be able to quit a 17-year job at the Post Office! \n" + "Thanks, Rob!\" - R.W., Detroit, Mi.\n"
			+ "\n" + "The Dallas Morning News - Aug, 1994 - \"This home business \n"
			+ "idea is new.. it can be a profitable income producer. Since \n"
			+ "it's 'remote,' it doesn't matter where you do it.\"\n" + "\n"
			+ "My staff and I are committed to making YOU successful. We \n"
			+ "KNOW how to do it, because we've done it ourselves for 10\n"
			+ "years. Let us show YOU how to make YOUR computer earn \n" + "money while YOU sleep!";

	public static final String NO_SPAM = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod "
			+ "tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo "
			+ "duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. "
			+ "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et "
			+ "dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet "
			+ "clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.";
}
